[package]
name = "Web"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
url = "2.2"
tokio = { version = "1", features = ["full"] }
scraper = "0.12"